### ISSUE TITLE
Write tests for YD-41 Sailing yacht

### ISSUE THREAD

**Issue by TAJD** [marinlauber/Python-VPP#1]
1. Write tests to confirm that the YD-41 yacht returns similar results to Larsson predictions.
2. Automate test production with CI/CD tools.

**Comment by TAJD** [comment]
Some numerical instability need to investigate source.

**Comment by drizham** [comment]
Is this project still active?

**Comment by MG-ng** [comment]
There are a couple of errors thrown when executed in codespaces, for example this : 

```
python benchmark/benchmark.py -g -o OUTPUT_NAME
Analysis set for TWS:  [5.83203733]
Analysis set for TWA:  [ 41.499       44.6203871   47.74177419  50.86316129  53.98454839
  57.10593548  60.22732258  63.34870968  66.47009677  69.59148387
  72.71287097  75.83425806  78.95564516  82.07703226  85.19841935
  88.31980645  91.44119355  94.56258065  97.68396774 100.80535484
 103.92674194 107.04812903 110.16951613 113.29090323 116.41229032
 119.53367742 122.65506452 125.77645161 128.89783871 132.01922581
 135.1406129  138.262     ]
Using sail quiver  ['YD41 + YD41', 'YD41 + YD41']
Sailing in TWS : 5.8
Sail Config :  YD41 + YD41
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:02<00:00, 12.33it/s]
Sail Config :  YD41 + YD41
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:01<00:00, 17.32it/s]

Optimization successful.
Traceback (most recent call last):
  File "/workspaces/Python-VPP/benchmark/benchmark.py", line 257, in <module>
    benchmark(parser.parse_args())
  File "/workspaces/Python-VPP/benchmark/benchmark.py", line 234, in benchmark
    calc[s] = compute(s, bm[gt][s][:, 0])
  File "/workspaces/Python-VPP/benchmark/benchmark.py", line 69, in compute
    res[i, :] = [twa , max(vpp.store[0, :, 0][i], vpp.store[0, :, 3][i])]
IndexError: index 3 is out of bounds for axis 2 with size 2
```

I'm not quite sure how it's supposed to be… Has anyone experienced this too?

**Comment by marinlauber** [comment]
Hi, you will need to be more specific, I never ran it in codespace so I don't expect it to work there.

**Comment by MG-ng** [comment]
Well, you fixed those errors in https://github.com/marinlauber/Python-VPP/commit/c83ff0f0917dd548a9e33c17d514979d557bf774
Thank you very much for that, it's running well now (also in codespaces fyi)!


What do you think about renaming BAD to BAS to achieve compatibility with the ORC International Measurement System? 
https://ocw.mit.edu/courses/2-996-sailing-yacht-design-13-734-fall-2003/6c7d5651c343bc595339da09f309306c_ims_rule_book.pdf (p. 4)
<img width="704" alt="page148_Fig7 19" src="https://github.com/marinlauber/Python-VPP/assets/45321071/bab64be9-afbd-4652-8cd9-69e8527b3ccb">

https://github.com/marinlauber/Python-VPP/blob/c83ff0f0917dd548a9e33c17d514979d557bf774/runVPP.py#L25
