### ISSUE TITLE
Roach in % ?

### ISSUE THREAD

**Issue by MG-ng** [marinlauber/Python-VPP#22]
https://github.com/marinlauber/Python-VPP/blob/d0088714cceda66bd1480cccff3eb3dc6edc3a62/src/SailMod.py#L66 

This line of code means that the roach is measured in percent right? 
It seems like this is in contraction to the book "Principles of yacht design - Larsson, Eliasson" (where you've got the "BAD" variable name from) as you can see in the picture below. 
There, I think, the roach is the maximum length of the perpendicular from the straight line between top and clew to the leech in mm: 

<img width="456" alt="Bildschirmfoto 2024-01-08 um 21 43 27" src="https://github.com/marinlauber/Python-VPP/assets/45321071/2ee15e70-42ff-4741-950a-78fb62cf496b">

What do you think?

**Comment by TAJD** [comment]
This is a useful observation that others will pick up on.

Perhaps a docstring to clarify the decision here might be useful for future readers - if there isn't a selected docstring style then [pandas](https://pandas.pydata.org/docs/development/contributing_docstring.html) is my go to style.

A user can also easily dimension this prior to running the simulation so a workaround is available.

**Comment by MG-ng** [comment]
@TAJD Do you mean something like this? 
https://github.com/marinlauber/Python-VPP/pull/23
