### ISSUE TITLE
Unresolved Reference

### ISSUE THREAD

**Issue by MG-ng** [marinlauber/Python-VPP#26]
https://github.com/marinlauber/Python-VPP/blob/91a4e2c56b1565ee582e3e3b1412081b46a1930d/src/HydroMod.py#L203-L204

Doesn't this have to be `self.fn` like before? 

https://github.com/marinlauber/Python-VPP/blob/91a4e2c56b1565ee582e3e3b1412081b46a1930d/src/HydroMod.py#L193

**Comment by marinlauber** [comment]
No, that wouldn't make sense, here `fn` stands for file name. But you are right that it's unused, it should be in the function arguments with a default `show_resistance(self, vb, fn="None")`, and we can rename it to `file_name` to make it clear.

**Comment by MG-ng** [comment]
Okay, thanks! #27
