### ISSUE TITLE
COG

### ISSUE THREAD

**Issue by Formula78** [marinlauber/Python-VPP#30]
How is the Vertical Center of Gravity considered? The boat currently reaches high heeling angles even in light winds.

**Comment by marinlauber** [comment]
It's considered upstream to construct the `righting_arm.json` file where the GZ curve of the boat is reported. I don't remember how the one for the YD41 was constructed in this case.

**Comment by TAJD** [comment]
@Formula78 is that enough information for you for right now?

**Comment by Formula78** [comment]
Yes, that was sufficient. I will take the GZ curve from a heeling calculation, or maybe there is anywhere an equation in the DSYHS for the heeling lever.
